### ISSUE TITLE
Backend tests - mejoras

### ISSUE THREAD

**Issue by fdodino** [Asta1986/TTIP-Grupo5-Docs#3]
Basado en [estos tests](https://github.com/alonsoem/TTIP-Grupo5-BackEnd/blob/8503541af51d2c8b448b9532d0e2b46c45fa2400/src/test/java/ar/edu/unq/ttip/alec/backend/webservices/BrokerControllerTests.java#L79)

- pueden usar `@DisplayName` para mejorar la legibilidad del test cuando se corre
- en lugar de testear que [aparezca el string `129`](https://github.com/alonsoem/TTIP-Grupo5-BackEnd/blob/8503541af51d2c8b448b9532d0e2b46c45fa2400/src/test/java/ar/edu/unq/ttip/alec/backend/webservices/BrokerControllerTests.java#L105) podrían hacer búsquedas por el path de JSON

```kt
    @Test
    fun `si buscamos un candidate existente, recibimos el candidate`() {
        val candidate = getCandidateDePrueba()
        mockMvc.perform(
            MockMvcRequestBuilders.get("/candidates/" + candidate.id)
                .contentType(MediaType.APPLICATION_JSON)
        )
        .andExpect(status().isOk)
        .andExpect(content().contentType("application/json"))
        .andExpect(jsonPath("$.nombre").value(CANDIDATE_NOMBRE))
    }
```

**Comment by lfir** [comment]
Corrected in [dfecfd385adc6c51ff98a62ab517c1ae99f266c2](https://github.com/alonsoem/TTIP-Grupo5-BackEnd/commit/dfecfd385adc6c51ff98a62ab517c1ae99f266c2)
